import { MigrationInterface, QueryRunner } from 'typeorm';

export default class couponPromo1692712498358 implements MigrationInterface {
  name = 'couponPromo1692712498358';

  public async up(queryRunner: QueryRunner): Promise<void> {
    /**
     * Drop fk
     */
    await queryRunner.query(
      `ALTER TABLE "promo_code" DROP CONSTRAINT "promo_code(fk):couponPromoCodeId_promoCodeId"`,
    );

    /**
     * Drop auto generated pk
     */
    await queryRunner.query(`ALTER TABLE "promo_code" DROP COLUMN "couponPromoCodeId"`);

    /**
     * Add fk on couponId ref couponId
     */
    await queryRunner.query(
      `ALTER TABLE "promo_code" ADD CONSTRAINT "promo_code(fk):couponId" FOREIGN KEY ("couponId") REFERENCES "coupon"("couponId") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    /**
     * Drop fk on couponId ref couponId
     */
    await queryRunner.query(`ALTER TABLE "promo_code" DROP CONSTRAINT "promo_code(fk):couponId"`);

    /**
     * Add autogenerated column for fk
     */
    await queryRunner.query(
      `ALTER TABLE "promo_code" ADD "couponPromoCodeId" character varying(30)`,
    );

    await queryRunner.query(
      `ALTER TABLE "promo_code" ADD CONSTRAINT "promo_code(fk):couponPromoCodeId_promoCodeId" FOREIGN KEY ("couponPromoCodeId") REFERENCES "promo_code"("promoCodeId") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }
}
