version: '3.7'

services:
  ijson:
    image: lega911/ijson
    container_name: ijson
    ports:
      - "8001:8001"

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  gateway:
    image: ghcr.io/lomray-software/microservices/gateway:latest-staging
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - configuration

  configuration:
    image: ghcr.io/lomray-software/microservices/configuration:latest-staging
    container_name: configuration
    environment:
      # from ./config.json
      MS_CONFIGS: '[{"microservice":"*","type":"db","params":{"host":"127.0.0.1","port":5432,"username":"postgres","password":"example"}},{"microservice":"authentication","type":"config","params":{"jwtOptions":{"secretKey":"DemoSecretKey"}}}]'
      # from ./middlewares.json
      MS_MIDDLEWARES: '[{"target":"gateway","targetMethod":"*","sender":"authentication","senderMethod":"token.identify","type":"request","params":{"type":"request","isRequired":true,"strategy":"transform","convertResult":{"payload.authentication.userId":"$middleware.userId","payload.authentication.isAuth":"$middleware.isAuth","payload.authentication.provider":"$middleware.provider"}}},{"target":"gateway","targetMethod":"*","sender":"authorization","senderMethod":"endpoint.enforce","type":"request","params":{"type":"request","isRequired":true,"isCleanResult":true,"strategy":"transform","reqParams":{"isInternal":true},"convertParams":{"userId":"$task.payload.authentication.userId","method":"$task.method","filterInput":"$task.params"},"convertResult":{".":"$middleware.filteredInput","payload":"$task.payload","payload.authorization.isAllow":"$middleware.isAllow","payload.authorization.filter":"$middleware.filters"}}},{"target":"gateway","targetMethod":"*","sender":"authorization","senderMethod":"endpoint.filter","type":"response","params":{"type":"response","isRequired":true,"isCleanResult":true,"strategy":"transform","reqParams":{"isInternal":true},"convertParams":{"type":"out","userId":"$task.payload.authentication.userId","method":"$task.method","filterInput":"$result"},"convertResult":{".":"$middleware.filtered","payload":"$task.payload"}}},{"target":"users","targetMethod":"identity-provider.sign-in","sender":"authentication","senderMethod":"token.create","type":"response","params":{"type":"response","isRequired":true,"strategy":"transform","convertParams":{"type":"jwt","userId":"$result.user.id","returnType":"cookies"},"convertResult":{"payload.cookies":"$middleware.payload","tokens.refresh":"$middleware.refresh"}}},{"target":"users","targetMethod":"user.sign-in","sender":"authentication","senderMethod":"token.create","type":"response","params":{"type":"response","isRequired":true,"strategy":"transform","convertParams":{"type":"jwt","userId":"$result.user.id","returnType":"cookies"},"convertResult":{"payload.cookies":"$middleware.payload","tokens.refresh":"$middleware.refresh"}}},{"target":"users","targetMethod":"user.sign-up","sender":"authentication","senderMethod":"token.create","type":"response","params":{"type":"response","isRequired":true,"strategy":"transform","convertParams":{"type":"jwt","userId":"$result.user.id","returnType":"cookies"},"convertResult":{"payload.cookies":"$middleware.payload","tokens.refresh":"$middleware.refresh"}}},{"target":"users","targetMethod":"user.sign-out","sender":"authentication","senderMethod":"token.remove","type":"response","params":{"type":"response","isRequired":true,"strategy":"transform","convertParams":{"query.where.userId":"$task.params.userId"}}}]'
    depends_on:
      - db

  authentication:
    image: ghcr.io/lomray-software/microservices/authentication:latest-staging
    container_name: authentication
    depends_on:
      - configuration

  authorization:
    image: ghcr.io/lomray-software/microservices/authorization:latest-staging
    container_name: authorization
    environment:
      MS_DEFAULT_PERMISSION_MIGRATION: 1
      MS_WORKERS: 2
    depends_on:
      - configuration

  users:
    image: ghcr.io/lomray-software/microservices/users:latest-staging
    container_name: users
    depends_on:
      - configuration
