version: '3.7'

services:
  configuration:
    image: ghcr.io/lomray-software/microservices/configuration:latest-staging
    container_name: configuration
    restart: always
    environment:
      DB_HOST: db
      MS_CONNECTION: $MS_CONNECTION
      MS_INIT_CONFIGS: $MS_INIT_CONFIGS
      MS_INIT_MIDDLEWARES: $MS_INIT_MIDDLEWARES

  gateway:
    image: ghcr.io/lomray-software/microservices/gateway:latest-staging
    container_name: gateway
    restart: always
    ports:
      - ${GATEWAY_PORT}:3000
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION

  authentication:
    image: ghcr.io/lomray-software/microservices/authentication:latest-staging
    container_name: authentication
    restart: always
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION

  authorization:
    image: ghcr.io/lomray-software/microservices/authorization:latest-staging
    container_name: authorization
    restart: always
    environment:
      MS_DEFAULT_PERMISSION_MIGRATION: $MS_DEFAULT_PERMISSION_MIGRATION
      MS_CONNECTION: $MS_CONNECTION
    depends_on:
      - configuration

  notification:
    image: ghcr.io/lomray-software/microservices/notification:latest-staging
    container_name: notification
    restart: always
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION

  users:
    image: ghcr.io/lomray-software/microservices/users:latest-staging
    container_name: users
    restart: always
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION
