version: '3.7'

services:
  configuration:
    image: ghcr.io/lomray-software/microservices/configuration:${VERSION_TAG}
    container_name: configuration
    restart: always
    environment:
      DB_HOST: db
      MS_CONNECTION: $MS_CONNECTION
      MS_INIT_CONFIGS: $MS_INIT_CONFIGS
      MS_INIT_MIDDLEWARES: $MS_INIT_MIDDLEWARES

  gateway:
    image: ghcr.io/lomray-software/microservices/gateway:${VERSION_TAG}
    container_name: gateway
    restart: always
    ports:
      - ${GATEWAY_PORT}:3000
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION

  authentication:
    image: ghcr.io/lomray-software/microservices/authentication:${VERSION_TAG}
    container_name: authentication
    restart: always
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION

  authorization:
    image: ghcr.io/lomray-software/microservices/authorization:${VERSION_TAG}
    container_name: authorization
    restart: always
    environment:
      MS_IMPORT_PERMISSION: $MS_IMPORT_PERMISSION
      MS_CONNECTION: $MS_CONNECTION
    depends_on:
      - configuration
    #volumes:
    #  - ./microservices/authorization/permissions:/var/www/lib/migrations/permissions/list

  cron:
    image: ghcr.io/lomray-software/microservices/cron:${VERSION_TAG}
    container_name: cron
    restart: always
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION
      MS_INIT_TASKS: $MS_INIT_TASKS

  notification:
    image: ghcr.io/lomray-software/microservices/notification:${VERSION_TAG}
    container_name: notification
    restart: always
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION

  users:
    image: ghcr.io/lomray-software/microservices/users:${VERSION_TAG}
    container_name: users
    restart: always
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION

  files:
    image: ghcr.io/lomray-software/microservices/files:${VERSION_TAG}
    container_name: files
    restart: always
    depends_on:
      - configuration
    environment:
      MS_CONNECTION: $MS_CONNECTION
