version: '3.7'

services:
  ijson:
    image: lega911/ijson
    container_name: ijson
    ports:
      - "8001:8001"

  gateway:
    image: ghcr.io/lomray-software/microservices/gateway:latest-staging
    container_name: gateway
