version: '3.7'

services:
  ijson:
    # ~ 70 MB memory
    image: lega911/ijson
    container_name: ijson
    ports:
      - "8001:8001"

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
