version: '3.7'

services:
  ijson:
    # ~ 70 MB memory
    image: lega911/ijson
    container_name: ijson
    ports:
      - "8001:8001"

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

# for testing opentelemetry
#  agent:
#    image: matthewpatell/opentelemetry-collector:latest
#    container_name: opentelemetry_collector
#    environment:
#      TEMPO_ENDPOINT: tempo-us-central1.grafana.net:443
#      TEMPO_BASIC_AUTH: FILL_THIS_FIELD
#      METRIC_ENDPOINT: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
#      METRIC_BASIC_AUTH: FILL_THIS_FIELD
#    ports:
#      - "4318:4318"
