### Creaete transaction
POST http://127.0.0.1:8001/ms/payment-stripe
Accept: application/json
Content-Type: application/json
## Success refund card: 58d82be8-80b0-4b7b-81ea-a1dc9af346c3
## Failed refund card: 5e219e6c-ea6a-4081-a8f1-8ab00977cb97

{
  "id": "1",
  "method": "stripe.create-payment-intent",
  "params": {
    "userId": "68827b31-33e9-45b5-bf9f-8823b993d0ef",
    "receiverId": "0b0be2e8-1013-4be8-8e7f-a27c4b0a5e45",
    "entityId": "9bea9620-b8fb-4675-a8cc-593a98b8ffe5",
    "cardId": "5e219e6c-ea6a-4081-a8f1-8ab00977cb97",
    "entityCost": 100,
    "feesPayer": "sender",
    "title": "9 refund failed",
    "applicationPaymentPercent": 3,
    "withTax": false
  }
}

### Refund custom amount
POST http://127.0.0.1:8001/ms/payment-stripe
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.refund",
  "params": {
    "transactionId": "pi_3OCWa6FpQjUWTpHe1cPPDiCC",
    "amount": 200
  }
}

### Refund revenue
POST http://127.0.0.1:8001/ms/payment-stripe
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.refund",
  "params": {
    "transactionId": "pi_3OCT0JFpQjUWTpHe01ks0b1T"
  }
}

### Refund entity cost with extra fees
POST http://127.0.0.1:8001/ms/payment-stripe
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.refund",
  "params": {
    "transactionId": "pi_3OCTWzFpQjUWTpHe1Fon6ebZ",
    "refundAmountType": "revenue"
  }
}

### Refund entity cost
POST http://127.0.0.1:8001/ms/payment-stripe
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.refund",
  "params": {
    "transactionId": "pi_3NgWTJAmQ4asS8PS0FfnAYKW"
  }
}
