### Build page
### Create page header
POST http://127.0.0.1:8001/ms/content
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "component.create",
  "params": {
    "fields": {
      "alias": "pageHeader",
      "title": "Page header",
      "schema": [
        {
          "name": "headerTitle",
          "title": "Header title",
          "type": "text"
        },
        {
          "name": "postNumber",
          "title": "Post number",
          "type": "number"
        }
      ]
    }
  }
}

### Create page content
POST http://127.0.0.1:8001/ms/content
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "component.create",
  "params": {
    "fields": {
      "alias": "pageContent",
      "title": "Page content",
      "schema": [
        {
          "name": "contentTitle",
          "title": "Content title",
          "type": "text"
        },
        {
          "name": "contentDate",
          "title": "Date of creation",
          "type": "date"
        },
        {
          "name": "contentDescription",
          "title": "Content description",
          "type": "richText"
        },
        {
          "name": "contentCreators",
          "type": "relation",
          "relation": {
            "microservice": "users",
            "entity": "user",
            "searchFields": [
              {
                "name": "firstName",
                "insensitive": true
              },
              {
                "name": "lastName",
                "insensitive": true
              }
            ],
            "idFields": [
              "id"
            ],
            "titleFields": [
              "firstName",
              "lastName"
            ],
            "hasMany": false
          }
        }
      ]
    }
  }
}

### Create page footer
POST http://127.0.0.1:8001/ms/content
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "component.create",
  "params": {
    "fields": {
      "alias": "pageFooter",
      "title": "Page footer",
      "schema": [
        {
          "name": "contactUsWithTheEmail",
          "title": "Contact us with the email",
          "type": "email"
        },
        {
          "name": "isThisPostRecommendedByUS",
          "title": "Is this post recommended by us",
          "type": "boolean"
        }
      ]
    }
  }
}

### Create page component
POST http://127.0.0.1:8001/ms/content
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "component.create",
  "params": {
    "fields": {
      "children": [
        {
          "id": "9a7aedb4-4b00-44b3-89a3-a535692d28d6"
        },
        {
          "id": "e6186469-a9a5-444c-812c-c801c95245b8"
        },
        {
          "id": "78567003-f8cb-4d92-8aab-d7c9dc88bf2e"
        }
      ],
      "alias": "blogPostPage",
      "title": "Blog post page",
      "schema": [
        {
          "id": "9a7aedb4-4b00-44b3-89a3-a535692d28d6",
          "name": "header",
          "type": "component",
          "hasMany": false
        },
        {
          "id": "e6186469-a9a5-444c-812c-c801c95245b8",
          "name": "content",
          "type": "component",
          "hasMany": false
        },
        {
          "id": "78567003-f8cb-4d92-8aab-d7c9dc88bf2e",
          "name": "footer",
          "type": "component",
          "hasMany": false
        },
        {
          "name": "options",
          "title": "Options",
          "type": "json"
        }
      ]
    }
  }
}

### Create single type for page
POST http://127.0.0.1:8001/ms/content
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "single-type.create",
  "params": {
    "fields": {
      "components": [
        {
          "id": "dff2719e-3c57-4248-9408-59af6287a568"
        }
      ],
      "title": "Page single type",
      "alias": "pageSingleType",
      "value": {
        "blogPostPage": {
          "id": "dff2719e-3c57-4248-9408-59af6287a568",
          "data": {
            "header": {
              "id": "9a7aedb4-4b00-44b3-89a3-a535692d28d6",
              "data": {
                "pageHeader": {
                  "id": "9a7aedb4-4b00-44b3-89a3-a535692d28d6",
                  "data": {
                    "headerTitle": "Cars",
                    "postNumber": 1
                  }
                }
              }
            },
            "content": {
              "id": "e6186469-a9a5-444c-812c-c801c95245b8",
              "data": {
                "pageContent": {
                  "id": "e6186469-a9a5-444c-812c-c801c95245b8",
                  "data": {
                    "contentTitle": "Green Lamborghini",
                    "contentDate": "2023-05-28T13:56:55.360Z",
                    "contentDescription": "contentTitle",
                    "contentCreators": [
                      "b9b61ca6-761b-4051-84b2-647a2262b78b",
                      "a5326de3-d04c-425c-8711-0f99fc031c67"
                    ]
                  }
                }
              }
            },
            "footer": {
              "id": "78567003-f8cb-4d92-8aab-d7c9dc88bf2e",
              "data": {
                "id": "78567003-f8cb-4d92-8aab-d7c9dc88bf2e",
                "pageFooter": {
                  "contactUsWithTheEmail": "contact@us.com",
                  "isThisPostRecommendedByUS": true
                }
              }
            },
            "options": {
              "timeZoneId": "America/Los_Angeles",
              "timeZoneName": "Pacific Daylight Time"
            }
          }
        }
      }
    }
  }
}

### View signle type
POST http://127.0.0.1:8001/ms/content
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "single-type.view",
  "params": {
    "query": {
      "where": {
        "id": "c59cdc52-86d0-4d61-bc8e-ab770fc1fd7b"
      }
    },
    "payload": {
      "expand": [
        "blogPostPage.content.pageContent.contentCreators"
      ]
    }
  }
}

### With authorization
POST http://127.0.0.1:3005
Accept: application/json
Content-Type: application/json
Authorization: Bearer admintokenooooooooooooooooooooon

{
  "id": "1",
  "method": "content.component.create",
  "params": {
    "fields": {
      "alias": "pageHeader",
      "title": "Page header",
      "schema": [
        {
          "name": "headerTitle",
          "title": "Header title",
          "type": "text"
        },
        {
          "name": "postNumber",
          "title": "Post number",
          "type": "number"
        }
      ]
    }
  }
}

### Create page content
POST http://127.0.0.1:3005
Accept: application/json
Content-Type: application/json
Authorization: Bearer admintokenooooooooooooooooooooon

{
  "id": "1",
  "method": "content.component.create",
  "params": {
    "fields": {
      "alias": "pageContent",
      "title": "Page content",
      "schema": [
        {
          "name": "contentTitle",
          "title": "Content title",
          "type": "text"
        },
        {
          "name": "contentDate",
          "title": "Date of creation",
          "type": "date"
        },
        {
          "name": "contentDescription",
          "title": "Content description",
          "type": "richText"
        },
        {
          "name": "contentCreators",
          "type": "relation",
          "relation": {
            "microservice": "users",
            "entity": "user",
            "searchFields": [
              {
                "name": "firstName",
                "insensitive": true
              },
              {
                "name": "lastName",
                "insensitive": true
              }
            ],
            "idFields": [
              "id"
            ],
            "titleFields": [
              "firstName",
              "lastName"
            ],
            "hasMany": false
          }
        }
      ]
    }
  }
}

### Create page footer
POST http://127.0.0.1:3005
Accept: application/json
Content-Type: application/json
Authorization: Bearer admintokenooooooooooooooooooooon

{
  "id": "1",
  "method": "content.component.create",
  "params": {
    "fields": {
      "alias": "pageFooter",
      "title": "Page footer",
      "schema": [
        {
          "name": "contactUsWithTheEmail",
          "title": "Contact us with the email",
          "type": "email"
        },
        {
          "name": "isThisPostRecommendedByUS",
          "title": "Is this post recommended by us",
          "type": "boolean"
        }
      ]
    }
  }
}

### Create page component
POST http://127.0.0.1:3005
Accept: application/json
Content-Type: application/json
Authorization: Bearer admintokenooooooooooooooooooooon

{
  "id": "1",
  "method": "content.component.create",
  "params": {
    "fields": {
      "children": [
        {
          "id": "ac63a3e6-bbb0-46e0-a0e4-74c2707914b8"
        },
        {
          "id": "a89d597f-cf22-4c3d-a549-98beac9fdd0b"
        },
        {
          "id": "523d17d1-f21d-4f7e-8dfe-6122e6fd4beb"
        }
      ],
      "alias": "blogPostPage",
      "title": "Blog post page",
      "schema": [
        {
          "id": "ac63a3e6-bbb0-46e0-a0e4-74c2707914b8",
          "name": "header",
          "type": "component",
          "hasMany": false
        },
        {
          "id": "a89d597f-cf22-4c3d-a549-98beac9fdd0b",
          "name": "content",
          "type": "component",
          "hasMany": false
        },
        {
          "id": "523d17d1-f21d-4f7e-8dfe-6122e6fd4beb",
          "name": "footer",
          "type": "component",
          "hasMany": false
        },
        {
          "name": "options",
          "title": "Options",
          "type": "json"
        }
      ]
    }
  }
}

### Create single type for page
POST http://127.0.0.1:3005
Accept: application/json
Content-Type: application/json
Authorization: Bearer admintokenooooooooooooooooooooon

{
  "id": "1",
  "method": "content.single-type.create",
  "params": {
    "fields": {
      "components": [
        {
          "id": "1b1fb70a-8e2a-4ed3-89f1-a89f453249d4"
        }
      ],
      "title": "Page single type",
      "alias": "pageSingleType",
      "value": {
        "blogPostPage": {
          "id": "1b1fb70a-8e2a-4ed3-89f1-a89f453249d4",
          "data": {
            "header": {
              "id": "ac63a3e6-bbb0-46e0-a0e4-74c2707914b8",
              "data": {
                "pageHeader": {
                  "id": "ac63a3e6-bbb0-46e0-a0e4-74c2707914b8",
                  "data": {
                    "headerTitle": "Cars",
                    "postNumber": 1
                  }
                }
              }
            },
            "content": {
              "id": "a89d597f-cf22-4c3d-a549-98beac9fdd0b",
              "data": {
                "pageContent": {
                  "id": "a89d597f-cf22-4c3d-a549-98beac9fdd0b",
                  "data": {
                    "contentTitle": "Green Lamborghini",
                    "contentDate": "2023-05-28T13:56:55.360Z",
                    "contentDescription": "contentTitle",
                    "contentCreators": [
                      "c06d7ad4-a4cc-4bfc-9b23-474e288113a3",
                      "cbd4d27f-2d97-451c-be98-fd4bbe099d64"
                    ]
                  }
                }
              }
            },
            "footer": {
              "id": "523d17d1-f21d-4f7e-8dfe-6122e6fd4beb",
              "data": {
                "id": "523d17d1-f21d-4f7e-8dfe-6122e6fd4beb",
                "pageFooter": {
                  "contactUsWithTheEmail": "contact@us.com",
                  "isThisPostRecommendedByUS": true
                }
              }
            },
            "options": {
              "timeZoneId": "America/Los_Angeles",
              "timeZoneName": "Pacific Daylight Time"
            }
          }
        }
      }
    }
  }
}

### Build singlt type dynamic model ref schema (permissions import, sync, export) and allow for user
POST http://127.0.0.1:8001/ms/content
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "meta",
  "params": {
    "payload": {
      "isInternal": true
    }
  }
}


### View signle type
POST http://127.0.0.1:3005
Accept: application/json
Content-Type: application/json
#Authorization: Bearer admintokenooooooooooooooooooooon
Authorization: Bearer usertokenoooooooooooooooooooooon

{
  "id": "1",
  "method": "content.single-type.view",
  "params": {
    "query": {
      "where": {
        "id": "e21e02ef-cdec-4515-b477-99f05acd0d16"
      }
    },
    "payload": {
      "expand": [
        "blogPostPage.content.pageContent.contentCreators"
      ]
    }
  }
}

### Additional
### Create single type for page with hasMany
POST http://127.0.0.1:8001/ms/content
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "single-type.create",
  "params": {
    "fields": {
      "components": [
        {
          "id": "e5d4c33f-cd63-437a-a76b-bd798121ce15"
        }
      ],
      "title": "Page single type",
      "alias": "pageSingleTypeNew",
      "value": {
        "blogPostPage": {
          "id": "e5d4c33f-cd63-437a-a76b-bd798121ce15",
          "data": {
            "header": {
              "id": "43edbae4-ec2f-4a32-a477-b1cfc8bb3673",
              "data": {
                "pageHeader": {
                  "id": "43edbae4-ec2f-4a32-a477-b1cfc8bb3673",
                  "data": {
                    "headerTitle": "Cars",
                    "postNumber": 1
                  }
                }
              }
            },
            "content": {
              "id": "cc896aa8-1734-4556-94c1-fcbf849d520c",
              "data": {
                "pageContent": {
                  "id": "cc896aa8-1734-4556-94c1-fcbf849d520c",
                  "data": [
                    {
                      "contentTitle": "Green Lamborghini",
                      "contentDate": "2023-05-28T13:56:55.360Z",
                      "contentDescription": "contentTitle1",
                      "contentCreators": [
                        "a5326de3-d04c-425c-8711-0f99fc031c67"
                      ]
                    },
                    {
                      "contentTitle": "Blue Lamborghini",
                      "contentDate": "2023-05-28T13:56:55.360Z",
                      "contentDescription": "contentTitle2",
                      "contentCreators": [
                        "b9b61ca6-761b-4051-84b2-647a2262b78b"
                      ]
                    }
                  ]
                }
              }
            },
            "footer": {
              "id": "1fddf950-159f-419c-b006-eb07a51f7857",
              "data": {
                "id": "1fddf950-159f-419c-b006-eb07a51f7857",
                "pageFooter": {
                  "contactUsWithTheEmail": "contact@us.com",
                  "isThisPostRecommendedByUS": true
                }
              }
            },
            "options": {
              "timeZoneId": "America/Los_Angeles",
              "timeZoneName": "Pacific Daylight Time"
            }
          }
        }
      }
    }
  }
}

### View signle type
POST http://127.0.0.1:8001/ms/content
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "single-type.view",
  "params": {
    "query": {
      "where": {
        "id": "8b4d7fa9-4f61-4f6f-9737-01546cd07b4e"
      }
    },
    "payload": {
      "expand": [
        "blogPostPage.content.pageContent.contentCreators"
      ]
    }
  }
}
