### Get unique active users
POST http://127.0.0.1:3000
Accept: application/json
Content-Type: application/json
Authorization: Bearer admintokenooooooooooooooooooooon

{
  "id": "1",
  "method": "authentication.token.count",
  "params": {
    "payload": {
      "authorization": {
        "filter": {
          "methodOptions": {
            "isAllowDistinct": true
          }
        }
      }
    },
    "query": {
      "attributes": [
        {
          "name": "userId",
          "isDistinct": true
        }
      ]
    }
  }
}
