### Get unique active users
POST http://127.0.0.1:3000
Accept: application/json
Content-Type: application/json
## Admin token
Authorization: Bearer admintokenooooooooooooooooooooon
## User token
#Authorization: Bearer usertokenooooooooooooooooooooooo

{
  "id": "1",
  "method": "authentication.token.count",
  "params": {
    "query": {
      "attributes": [
        {
          "name": "userId",
          "isDistinct": true
        }
      ]
    }
  }
}

### Change user password as an application admin
POST http://127.0.0.1:3000
Accept: application/json
Content-Type: application/json
## Admin token
Authorization: Bearer admintokenooooooooooooooooooooon

{
  "id": "1",
  "method": "users.user.change-password",
  "params": {
    "userId": "68827b31-33e9-45b5-bf9f-8823b993d0ef",
    "newPassword": "123456789!A",
    "allowedByAdmin": true
  }
}

