### Get unique active users
POST http://127.0.0.1:3000
Accept: application/json
Content-Type: application/json
## Admin token
Authorization: Bearer admintokenooooooooooooooooooooon
## User token
#Authorization: Bearer usertokenooooooooooooooooooooooo

{
  "id": "1",
  "method": "authentication.token.count",
  "params": {
    "query": {
      "attributes": [
        {
          "name": "userId",
          "isDistinct": true
        }
      ]
    }
  }
}
