### Creaete transaction
POST http://127.0.0.1:8001/ms/payment-stripe
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.create-payment-intent",
  "params": {
    "userId": "68827b31-33e9-45b5-bf9f-8823b993d0ef",
    "receiverId": "0b0be2e8-1013-4be8-8e7f-a27c4b0a5e45",
    "entityId": "entity08-ecd6-483a-9117-2af2e104b5f8",
    "entityCost": 100,
    "feesPayer": "sender",
    "title": "ticket",
    "applicationPaymentPercent": 3,
    "additionalFeesPercent": {
      "receiver": 5,
      "sender": 0
    }
  }
}

### Refund revenue
POST http://127.0.0.1:8001/ms/payment-stripe
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.refund",
  "params": {
    "transactionId": "pi_3NgXZSAmQ4asS8PS1ApUuPSI"
  }
}

### Refund entity cost
POST http://127.0.0.1:8001/ms/payment-stripe
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.refund",
  "params": {
    "transactionId": "pi_3NgWTJAmQ4asS8PS0FfnAYKW"
  }
}
