ARG  FROM_TAG=latest
FROM ghcr.io/lomray-software/microservices/authorization:${FROM_TAG}

MAINTAINER Yarmaliuk Mikhail <mikhail.yarmaliuk@lomray.com>

ENV WEB_PATH=/var/www
WORKDIR $WEB_PATH

# make some actions

