### Full account setup flow
### Step 1. Create customer
POST http://127.0.0.1:8001/ms/payment
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "customer.create",
  "params": {
    "userId": "admif8f1-17f8-4501-9de2-a6e775ea39f3"
  }
}

### Step 2. Stripe setup intent
POST http://127.0.0.1:8001/ms/payment
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.setup-intent",
  "params": {
    "userId": "admif8f1-17f8-4501-9de2-a6e775ea39f3"
  }
}

### Step 3. Connect accout (Setup bank account)
POST http://127.0.0.1:8001/ms/payment
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.connect-account",
  "params": {
    "userId": "admif8f1-17f8-4501-9de2-a6e775ea39f3",
    "email": "jegupkvqcvkutrm@internetkeno.com",
    "accountType": "standard",
    "refreshUrl": "https://example.com",
    "returnUrl": "https://example.com"
  }
}

### Step 4. Create PaymentIntent (Pay 100$)
POST http://127.0.0.1:8001/ms/payment
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "stripe.create-payment-intent",
  "params": {
    "userId": "userf8f1-17f8-4501-9de2-a6e775ea39f3",
    "totalAmount": 110,
    "receiverId": "admif8f1-17f8-4501-9de2-a6e775ea39f3",
    "title": "new",
    "entityId": "entity08-ecd6-483a-9117-2af2e104b5f8"
  }
}
