### Step 1.1 Create notice all task
POST http://127.0.0.1:8001/ms/notification
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "task.create",
  "params": {
    "fields": {
      "type": "noticeAll",
      "notices": [
        {
          "title": "1 task notice all",
          "description": "1 task notice all description",
          "type": "announce",
          "params": {
            "status": "warning",
            "isTemplate": true
          }
        }
      ]
    }
  }
}

### Step 1.2. Create email all task
POST http://127.0.0.1:8001/ms/notification
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "task.create",
  "params": {
    "fields": {
      "type": "emailAll",
      "messages": [
        {
          "html": "<p>1 task email all</p>",
          "subject": "1 task email all subject",
          "text": "1 task email all text",
          "type": "email",
          "params": {
            "isTemplate": true
          }
        }
      ]
    }
  }
}

### Step 1.3. Create email all task with full check up mode
POST http://127.0.0.1:8001/ms/notification
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "task.create",
  "params": {
    "fields": {
      "type": "emailAll",
      "mode": "fullCheckUp",
      "messages": [
        {
          "html": "<p>1 task email all</p>",
          "subject": "1 task email all subject",
          "text": "1 task email all text",
          "type": "email",
          "params": {
            "isTemplate": true
          }
        }
      ]
    }
  }
}

### Step 1.4. Create email group task
POST http://127.0.0.1:8001/ms/notification
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "task.create",
  "params": {
    "fields": {
      "type": "emailGroup",
      "messages": [
        {
          "html": "<p>1 task email all</p>",
          "subject": "1 task email all subject",
          "text": "1 task email all text",
          "type": "email",
          "params": {
            "isTemplate": true
          }
        }
      ],
      "recipients": [
        {
          "userId": "7bf97098-c84e-4b41-a8d8-0c628b957ff3"
        },
        {
          "userId": "5b86356f-bea2-469b-8a82-7566f369a1e0"
        },
        {
          "userId": "6e6ed89f-637f-4fd6-86c2-95ef706cacf3"
        }
      ]
    }
  }
}

### Step 2. Execute cron task - task process
POST http://127.0.0.1:8001/ms/notification
Accept: application/json
Content-Type: application/json

{
  "id": "1",
  "method": "job.task.process",
  "params": {
  }
}
