name: Check PR

on:
  pull_request:
    branches: [ prod, staging ]

jobs:
  changed-microservices:
    name: Get changed microservices
    runs-on: ubuntu-18.04
    outputs:
      microservices: ${{ steps.microservices.outputs.list }}

    steps:
      - uses: actions/checkout@v2

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - id: files
        uses: Ana06/get-changed-files@v2.1.0
        with:
          format: 'json'

      - id: microservices
        run: ./.github/get-changed-microservices.sh
        env:
          FILES: '${{ steps.files.outputs.all }}'

  checks:
    name: Run code checks
    needs: changed-microservices
    runs-on: ubuntu-18.04
    if: needs.changed-microservices.outputs.microservices != ''

    strategy:
      matrix:
        microservice: ${{ fromJson(needs.changed-microservices.outputs.microservices) }}

    env:
      MICROSERVICE_NAME: ${{ matrix.microservice }}

    steps:
      - uses: actions/checkout@v2

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Install global dependencies
        run: npm ci

      - name: Install microservice dependencies
        run: npm run global-install
        env:
          ONLY: ${{ env.MICROSERVICE_NAME }}

      - name: Check microservice eslint
        run: npm run lint:check
        env:
          ONLY: ${{ env.MICROSERVICE_NAME }}

      - name: Check microservice typescript
        run: npm run ts:check
        env:
          ONLY: ${{ env.MICROSERVICE_NAME }}

      - name: Run microservices tests
        run: npm run test
        env:
          ONLY: ${{ env.MICROSERVICE_NAME }}
