name: Check PR

on:
  pull_request:
    branches: [ staging ]

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Check eslint
        run: npm run lint:check

      - name: Typescript check
        run: npm run ts:check

      - name: Run tests
        run: npm run tests
